#!/bin/bash
# ═══════════════════════════════════════════════════════════
#  email_alert.sh — Email-Ready Alert Formatter
#  Formats all alerts into a clean email report.
#  Can send via sendmail/mail if configured,
#  or saves to file for manual sending.
#  Usage: bash scripts/alerts/email_alert.sh
# ═══════════════════════════════════════════════════════════

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$PROJECT_ROOT/config.sh"
source "$UTILS_DIR/logger.sh"

# ── Email settings (edit these) ──
EMAIL_TO="admin@yourserver.com"
EMAIL_FROM="pipeline@yourserver.com"
EMAIL_SUBJECT="[PIPELINE ALERT] Security Report - $(date '+%Y-%m-%d')"
EMAIL_FILE="$REPORTS_DIR/email_report.txt"

# ════════════════════════════════════════
# BUILD EMAIL BODY
# ════════════════════════════════════════
build_email_body() {
    local critical_count warning_count total_lines
    critical_count=$(wc -l < "$CRITICAL_ALERTS" 2>/dev/null || echo 0)
    warning_count=$(wc -l < "$WARNING_ALERTS"   2>/dev/null || echo 0)
    total_lines=$(grep -v "^#" "$RAW_COLLECTED" 2>/dev/null | wc -l || echo 0)

    > "$EMAIL_FILE"
    {
        echo "To: $EMAIL_TO"
        echo "From: $EMAIL_FROM"
        echo "Subject: $EMAIL_SUBJECT"
        echo "Content-Type: text/plain"
        echo ""
        echo "════════════════════════════════════════════"
        echo "   SECURITY PIPELINE ALERT REPORT"
        echo "   $(date '+%A, %B %d, %Y at %H:%M:%S')"
        echo "════════════════════════════════════════════"
        echo ""
        echo "EXECUTIVE SUMMARY"
        echo "─────────────────"
        echo "  Log lines processed:  $total_lines"
        echo "  Critical alerts:      $critical_count"
        echo "  Warning alerts:       $warning_count"
        echo "  Pipeline version:     $PIPELINE_VERSION"
        echo ""

        # Status indicator
        if [ "$critical_count" -gt 0 ]; then
            echo "  STATUS: ⚠ ACTION REQUIRED — Critical threats detected!"
        else
            echo "  STATUS: ✔ System operating normally"
        fi

        echo ""
        echo "CRITICAL ALERTS"
        echo "───────────────"
        if [ -s "$CRITICAL_ALERTS" ]; then
            cat "$CRITICAL_ALERTS"
        else
            echo "  No critical alerts."
        fi

        echo ""
        echo "WARNING ALERTS"
        echo "──────────────"
        if [ -s "$WARNING_ALERTS" ]; then
            cat "$WARNING_ALERTS"
        else
            echo "  No warnings."
        fi

        echo ""
        echo "ANOMALY BREAKDOWN"
        echo "─────────────────"
        if [ -f "$ANOMALY_COUNTS" ]; then
            cat "$ANOMALY_COUNTS"
        fi

        echo ""
        echo "TOP SUSPICIOUS IPs"
        echo "──────────────────"
        if [ -f "$IP_SUMMARY" ]; then
            head -15 "$IP_SUMMARY"
        fi

        echo ""
        echo "RECOMMENDED ACTIONS"
        echo "───────────────────"
        if [ "$critical_count" -gt 0 ]; then
            echo "  1. Review critical_alerts.txt immediately"
            echo "  2. Block suspicious IPs using your firewall"
            echo "  3. Check server error logs for root cause"
            echo "  4. Run: bash scripts/alerts/threshold_checker.sh scan"
        else
            echo "  1. Continue monitoring normally"
            echo "  2. Review warning alerts when convenient"
        fi

        echo ""
        echo "REPORT FILES"
        echo "────────────"
        echo "  Full report:     $FINAL_SUMMARY"
        echo "  Critical alerts: $CRITICAL_ALERTS"
        echo "  Pipeline log:    $PIPELINE_LOG"
        echo ""
        echo "════════════════════════════════════════════"
        echo "  Generated by Multi-Stage Pipeline v$PIPELINE_VERSION"
        echo "  $(date '+%Y-%m-%d %H:%M:%S')"
        echo "════════════════════════════════════════════"
    } >> "$EMAIL_FILE"
}

# ════════════════════════════════════════
# TRY TO SEND EMAIL
# Falls back to file-only if mail not set up
# ════════════════════════════════════════
send_email() {
    if command -v mail &>/dev/null; then
        log_info "Sending email to $EMAIL_TO..."
        mail -s "$EMAIL_SUBJECT" "$EMAIL_TO" < "$EMAIL_FILE"
        log_success "Email sent to $EMAIL_TO"
    elif command -v sendmail &>/dev/null; then
        log_info "Sending via sendmail..."
        sendmail "$EMAIL_TO" < "$EMAIL_FILE"
        log_success "Email sent via sendmail"
    else
        log_warn "No mail client found — email saved to file only"
        log_info "To send manually, configure 'mail' or 'sendmail'"
        log_info "Or copy contents of: $EMAIL_FILE"
    fi
}

# ════════════════════════════════════════
# MAIN
# ════════════════════════════════════════
main() {
    init_logger
    log_section "Email Alert Formatter"

    build_email_body
    log_success "Email report built: $EMAIL_FILE"

    send_email

    echo ""
    log_info "Preview of email report:"
    echo ""
    cat "$EMAIL_FILE"
}

main "$@"
